package Security;

// Creation Date: May 29, 2026. at 3:35 AM
// Last Modified: May 29, 2026. at  3:38 AM

class EncryptionHelper {
    //=======VARIABLES=======//

    //=======CONSTRUCTOR=======// NOTE: IN ORDER TO USE THIS FILES WE NEED A CONSTRUCTOR TO CREATE INSTANCES FROM OTHER FILES

    //==========GETTERS==========\\ NOTE: TO ACCESS THE PRIVATE VARIABLES AND USE IT TO OTHER FILES
    static encrypt(String data) {
        //! WHAT?? PLEASE CHECK THE PROMPT IT LITERALLY SAYS STATIC
    }

    //==========SETTERS==========\\ NOTE: CHANGES THE VARIABLES ON THIS FILE

    //===========METHODS===========\\ NOTE: THIS ARE THE SPECIFIC PROCESS IN ORDER TO MEET THE DESIRED RESULTS
}


// TODO: YOU LEFT HERE!!!!
// TODO: YOU WERE CONFUSED AT WHY CLAUDE GAVE US THIS PROMPT WHEN LITERALLY STATIC CANT BE CALLED SINCE THE CLASS IS PACKAGE-PRIVATE